wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.9.16
    start_time: 1680291751.377196
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 9
      - 41
      - 50
      - 53
      - 55
      - 80
      3:
      - 2
      - 7
      - 23
      4: 3.9.16
      5: 0.14.0
      8:
      - 3
      - 5
